config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users', to: 'devise/registrations#new'
    post '/users/guest_sign_in', to: 'users#guest_sign_in'
  end
  root to: "time_content#index"
  resources :users, only: [:show]
  resources :time_content do
    collection do
     get 'keyword_search', 'detail_search'
     get 'past_record'
     get 'support_content_registration'
     get 'support_search'
     get 'support_record'
     get 'support_calender'
    end
  end

end

app/models/time_content.rb
class TimeContent < ApplicationRecord
  before_save :set_time_zone

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :content
  belongs_to :ensure

  class << self
    def content_data
      @time_contents = TimeContent.all
      content_graph_data = {}
      @time_contents.each_with_index do |time_content, index|
        content_graph_data = { time_content.content.name => 0 } if index.zero?
        if content_graph_data.key?(time_content.content.name)
          content_graph_data[time_content.content.name] += 1 * (time_content.finish_time - time_content.begin_time) / 3600
        else
          content_graph_data[time_content.content.name] = 1 * (time_content.finish_time - time_content.begin_time) / 3600
        end
      end
      content_graph_data
    end

    def background_color_content_data
      @time_contents = TimeContent.all
      content_graph_data = {}
      background_colors = []
      @time_contents.each_with_index do |time_content, index|
        if index.zero?
          content_graph_data = { time_content.content.name => 0 }
          background_colors << time_content.content.backcolor
        end
        if content_graph_data.key?(time_content.content.name)
          content_graph_data[time_content.content.name] += 1
        else
          content_graph_data[time_content.content.name] = 1
          background_colors << time_content.content.backcolor
        end
      end
      background_colors
    end
  end

  with_options numericality: { other_than: 1, message: 'を選択してください' } do
    validates :content_id
    validates :ensure_id
  end

  with_options presence: true do
    validates :detail
    validates :start_time
    validates :begin_time, uniqueness: { scope: [:user_id, :begin_time, :start_time] }
    validates :finish_time, uniqueness: { scope: [:user_id, :finish_time, :start_time] }
  end

  validate :begin_finish_check
  validate :begin_check
  validate :finish_check
  validate :begin_time_from_to
  validate :finish_time_from_to
  validate :begin_finish_not_overlap

  def begin_finish_check
    if Date.today && (begin_time.strftime('%H:%M') > finish_time.strftime('%H:%M'))
      errors.add(:finish_time, 'は開始時刻より遅い時間を選択してください')
    end
  end

  def begin_check
    if start_time.today? && (begin_time.strftime('%H:%M') > Time.now.strftime('%H:%M'))
      errors.add(:begin_time,
                 'は現在時刻より早い時間を選択してください')
    end
  end

  def finish_check
    if start_time.today? && (finish_time.strftime('%H:%M') > Time.now.strftime('%H:%M'))
      errors.add(:finish_time,
                 'は現在時刻より早い時間を選択してください')
    end
  end

  def begin_time_from_to
    if begin_time.strftime('%H:%M') < '06:00' || begin_time.strftime('%H:%M') > '21:45'
      errors.add(:begin_time,
                 'は6時から21時45分までの時間を選択してください')
    end
  end

  def finish_time_from_to
    if finish_time.strftime('%H:%M') < '06:15' || finish_time.strftime('%H:%M') > '22:00'
      errors.add(:finish_time,
                 'は6時15分から22時までの時間を選択してください')
    end
  end

  def begin_finish_not_overlap
    return unless begin_time && finish_time

    if TimeContent.where(user_id: user_id, start_time: start_time).where('begin_time < ?', finish_time.strftime('%H:%M')).where(
      'finish_time > ?', begin_time.strftime('%H:%M')
    ).where.not(id: id).exists?
      errors.add(:base, '「開始時間」もしくは「終了時間」が登録済みの時間と重複しています')
    end
  end

  def set_time_zone
    year = Date.today.year
    month = Date.today.month
    day = Date.today.day

    self.begin_time = begin_time.change(year: year, month: month, day: day)
    self.finish_time = finish_time.change(year: year, month: month, day: day)
  end

  belongs_to :user
end

app/controllers/time_content_controller.rb
class TimeContentController < ApplicationController
  before_action :authenticate_user!, except: [:index, :support_content_registration, :support_search, :support_record, :support_calender]
  before_action :set_time_content, only: [:show, :edit, :update, :destroy]
  before_action :move_into_index, only: [:show, :edit]
  before_action :search_time_content, only: [:index, :show, :keyword_search, :detail_search]

  def index
    @time_contents = TimeContent.where(user_id: current_user)
    # @time_contents = TimeContent.all #1つのカレンダーでユーザー全員の内容を閲覧
    @day = Date.today
    @month = Date.today.all_month

    @content_month_graph_data = TimeContent.where(user_id: current_user, start_time: @month).order('content_id ASC').content_data
    @background_month_colors = TimeContent.where(user_id: current_user,
                                                 start_time: @month).order('content_id ASC').background_color_content_data

    @content_month_reduce_graph_data = TimeContent.where(user_id: current_user, ensure_id: 3,
                                                         start_time: @month).order('content_id ASC').content_data
    @background_month_reduce_colors = TimeContent.where(user_id: current_user, ensure_id: 3,
                                                        start_time: @month).order('content_id ASC').background_color_content_data

    @content_day_reduce_graph_data = TimeContent.where(user_id: current_user, ensure_id: 3,
                                                       start_time: @day).order('content_id ASC').content_data
    @background_day_reduce_colors = TimeContent.where(user_id: current_user, ensure_id: 3,
                                                      start_time: @day).order('content_id ASC').background_color_content_data

    @content_day_graph_data = TimeContent.where(user_id: current_user, start_time: @day).order('content_id ASC').content_data
    @background_colors = TimeContent.where(user_id: current_user,
                                           start_time: @day).order('content_id ASC').background_color_content_data

    @day_total_time = TimeContent.where(user_id: current_user, start_time: @day).order('content_id ASC').content_data
    @day_reduce_total_time = TimeContent.where(user_id: current_user, ensure_id: 3,
                                               start_time: @day).order('content_id ASC').content_data
    @month_reduce_total_time = TimeContent.where(user_id: current_user, ensure_id: 3,
                                                 start_time: @month).order('content_id ASC').content_data
    @month_total_time = TimeContent.where(user_id: current_user, start_time: @month).order('content_id ASC').content_data
  end

  def new
    @time_content = TimeContent.new
  end

  def create
    @time_content = TimeContent.new(time_content_params)
    if @time_content.save
      flash[:notice] = '内容を登録しました'
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @time_content.update(time_content_params)
      flash[:success] = '内容を編集しました'
      redirect_to time_content_path
    else
      render :edit
    end
  end

  def destroy
    redirect_to root_path if @time_content.destroy
  end

  def keyword_search
    @results = @p.result.includes(:user)
  end

  def detail_search
    @results = @p.result.includes(:user)
    set_detail_search_column
  end

  def past_record
    @yesterday = Date.yesterday
    @last_week = Date.today.last_week.all_week
    @week = Date.today.all_week
    @last_month = Date.today.last_month.all_month
    @friday = Date.today.prev_occurring(:friday)
    @saturday = Date.today.prev_occurring(:saturday)
    @task_saturday = TimeContent.where(user_id: current_user, start_time: Date.today.prev_occurring(:saturday))
    @task_sunday = TimeContent.where(user_id: current_user, start_time: Date.today.prev_occurring(:sunday))

    @content_yesterday_graph_data = TimeContent.where(user_id: current_user,
                                                      start_time: @yesterday).order('content_id ASC').content_data
    @background_yesterday_colors = TimeContent.where(user_id: current_user,
                                                     start_time: @yesterday).order('content_id ASC').background_color_content_data

    @content_friday_graph_data = TimeContent.where(user_id: current_user,
                                                   start_time: @friday).order('content_id ASC').content_data
    @background_friday_colors = TimeContent.where(user_id: current_user,
                                                  start_time: @friday).order('content_id ASC').background_color_content_data

    @content_saturday_graph_data = TimeContent.where(user_id: current_user,
                                                     start_time: @saturday).order('content_id ASC').content_data
    @background_saturday_colors = TimeContent.where(user_id: current_user,
                                                    start_time: @saturday).order('content_id ASC').background_color_content_data

    @content_week_graph_data = TimeContent.where(user_id: current_user,
                                                 start_time: @week).order('content_id ASC').content_data
    @background_week_colors = TimeContent.where(user_id: current_user,
                                                start_time: @week).order('content_id ASC').background_color_content_data

    @content_last_week_graph_data = TimeContent.where(user_id: current_user,
                                                      start_time: @last_week).order('content_id ASC').content_data
    @background_last_week_colors = TimeContent.where(user_id: current_user,
                                                     start_time: @last_week).order('content_id ASC').background_color_content_data

    @content_last_month_graph_data = TimeContent.where(user_id: current_user,
                                                       start_time: @last_week).order('content_id ASC').content_data
    @background_last_month_colors = TimeContent.where(user_id: current_user,
                                                      start_time: @last_week).order('content_id ASC').background_color_content_data

    @content_yesterday_reduce_graph_data = TimeContent.where(user_id: current_user, ensure_id: 3,
                                                             start_time: @yesterday).order('content_id ASC').content_data
    @background_yesterday_reduce_colors = TimeContent.where(user_id: current_user, ensure_id: 3,
                                                            start_time: @yesterday).order('content_id ASC').background_color_content_data

    @content_friday_reduce_graph_data = TimeContent.where(user_id: current_user, ensure_id: 3,
                                                          start_time: @friday).order('content_id ASC').content_data
    @background_friday_reduce_colors = TimeContent.where(user_id: current_user, ensure_id: 3,
                                                         start_time: @friday).order('content_id ASC').background_color_content_data

    @content_saturday_reduce_graph_data = TimeContent.where(user_id: current_user, ensure_id: 3,
                                                            start_time: @saturday).order('content_id ASC').content_data
    @background_saturday_reduce_colors = TimeContent.where(user_id: current_user, ensure_id: 3,
                                                           start_time: @saturday).order('content_id ASC').background_color_content_data

    @content_week_reduce_graph_data = TimeContent.where(user_id: current_user, ensure_id: 3,
                                                        start_time: @week).order('content_id ASC').content_data
    @background_week_reduce_colors = TimeContent.where(user_id: current_user, ensure_id: 3,
                                                       start_time: @week).order('content_id ASC').background_color_content_data

    @content_last_week_reduce_graph_data = TimeContent.where(user_id: current_user, ensure_id: 3,
                                                             start_time: @last_week).order('content_id ASC').content_data
    @background_last_week_reduce_colors = TimeContent.where(user_id: current_user, ensure_id: 3,
                                                            start_time: @last_week).order('content_id ASC').background_color_content_data

    @content_last_month_reduce_graph_data = TimeContent.where(user_id: current_user, ensure_id: 3,
                                                              start_time: @last_month).order('content_id ASC').content_data
    @background_last_month_reduce_colors = TimeContent.where(user_id: current_user, ensure_id: 3,
                                                             start_time: @last_month).order('content_id ASC').background_color_content_data

    @yesterday_total_time = TimeContent.where(user_id: current_user, start_time: @yesterday).order('content_id ASC').content_data
    @yesterday_reduce_total_time = TimeContent.where(user_id: current_user, ensure_id: 3,
                                                     start_time: @yesterday).order('content_id ASC').content_data

    @friday_total_time = TimeContent.where(user_id: current_user, start_time: @friday).order('content_id ASC').content_data
    @friday_reduce_total_time = TimeContent.where(user_id: current_user, ensure_id: 3,
                                                  start_time: @friday).order('content_id ASC').content_data

    @saturday_total_time = TimeContent.where(user_id: current_user, start_time: @saturday).order('content_id ASC').content_data
    @saturday_reduce_total_time = TimeContent.where(user_id: current_user, ensure_id: 3,
                                                    start_time: @saturday).order('content_id ASC').content_data

app/helpers/time_content_helper.rb
module TimeContentHelper
end

app/views/time_content/detail_search.html.erb
<div class="detail-search_form">
  <h1 class="detail-search-title">詳細検索</h1><br><br>
    <%= search_form_for @p, url: keyword_search_time_content_index_path do |f| %>

      <div class="start_time_field">
        <%= f.label :start_time_eq, '日付：' %> 
        <%= f.collection_select :start_time_gteq, @start_time, :start_time, :start_time, {include_blank: '指定なし'}, {class: "start_time_eq_from_search"} %>
        <div class= "from_to">~</div>
        <%= f.collection_select :start_time_lteq, @start_time, :start_time, :start_time, {include_blank: '指定なし'}, {class: "start_time_eq_to_search"} %>
      </div><br><br>
      
      <div class="start_time_field">
        <%= f.label :begin_time_eq, '実施時間：' %> 
        <%= f.collection_select :begin_time_eq, @begin_time, :begin_time, :begin_time, {include_blank: '指定なし'}, {class: "time_step_eq_from_search"} %> 
        <div class= "from_to">~</div>
        <%= f.collection_select :finish_time_eq, @finish_time, :finish_time, :finish_time, {include_blank: '指定なし'}, {class: "time_step_eq_to_search"} %> 
      </div><br><br>
      
      <div class="content_field">
        <%= f.label :content_id_eq, '実施内容：' %> 
        <%= f.collection_select :content_id_eq, Content.all, :id, :name, {include_blank: '指定なし'}, {class: "content_eq_search"} %> 
      </div><br><br>
      
      <div class="ensure_field">
        <%= f.label :ensure_id_eq, '実施できる人：' %> 
        <%= f.collection_select :ensure_id_eq, Ensure.all, :id, :name, {include_blank: '指定なし'}, {class: "ensure_eq_search"} %> 
      </div><br><br>

      <div class="detail_field">
      <%= f.label :detail_cont, 'キーワード：' %> 
      <%= f.text_field :detail_cont, class: 'input-box', placeholder:'キーワードから探す',class: "detail_cont_search" %>
      </div><br><br>
      
      <%= f.submit '検索',class: "detail_submit" %> 
      <br><br><br>
    <% end %> 
    <%= link_to 'トップページへ戻る', root_path, class: "back_btn" %><br><br>
</div>

app/views/time_content/edit.html.erb
<h1 class="time_content_title">【編集】今日の仕事内容と時間</h1>

<%= form_with(model: @time_content, url: time_content_path(@time_content.id), local: true) do |f| %>
<%= render 'shared/error_messages', model: f.object %>

  <div class="time_content_detail_title_1">
    <%= f.label :今日の日付, {:class => "date_title_style"} %>
    <%= f.label :開始時間, {:class => "begin_time_title_style"} %>
    <%= f.label :終了時間, {:class => "finish_time_title_style"} %> 
    <%= f.label :実施内容, {:class => "content_title_style"} %>
    <%= f.label :実施できる人, {:class => "ensure_title_style"} %>
  </div>

  <div class="time_and_content">
    <div class="date">
      <% if @time_content.start_time == nil %>
        <%= f.date_field :start_time, value: Date.today, class: "date_style"  %>
      <% elsif @time_content.start_time != nil %>
        <%= f.date_field :start_time, class: "date_style"  %>
      <% end %>
    </div>

    <div class="begin_time"> 
      <%= f.time_select(:begin_time, { prompt:'--', time_separator: ':', start_hour: 6, end_hour: 22, minute_step: 15, ignore_data: true}, {class: "begin_time_style"} ) %>
    </div>
 
    <div class="finish_time"> 
      <%= f.time_select(:finish_time, { prompt:'--', time_separator: ':', start_hour: 6, end_hour: 22, minute_step: 15, ignore_data: true}, {class: "begin_time_style"} ) %>
    </div>
    
    <div class="content">
      <%= f.collection_select(:content_id, Content.all, :id, :name, {}, {:class => "content_style"}) %>
    </div>

     <div class="ensure">
      <%= f.collection_select(:ensure_id, Ensure.all, :id, :name, {}, {:class => "ensure_style"}) %>
    </div>
  </div>

  <div class="time_content_detail_title_2">   
    <%= f.label :仕事詳細 %>
  </div>

  <div class="time_and_content_detail" >
    <div class="detial">
      <%= f.text_area :detail, {:class => "detail_style"} %>
    </div>
  </div>
    
  <div class="submit_btn">
    <div class="submit">
      <%= f.submit "登録", {:class => "submit_style"} %>
    </div>
  </div>
  <div class="edit_back_btn_form" >
    <%= link_to '詳細検索ページへ戻る', detail_search_time_content_index_path, class: "edit_back_btn_detail" %><br><br>
  </div><br>

<% end %>

app/views/time_content/index.html.erb
<main class="main">
  <div class="inner">
    <% if user_signed_in? %>
      <% if flash[:notice] %>
        <div class="notifications">
          <p class="notice"><%= flash[:notice] %></p>
        </div>
      <% end %>
      
      <div class="search_title">
        <h2 class="new_content_btn_title">
          新規登録ボタン
        </h2>
        <h2 class="keyword_search_title">
          キーワード検索(仕事詳細内容)
        </h2>
        <h2 class="detail_search_title">
          詳細検索ボタン
        </h2>
      </div>
      <div class="search_content">
        <%= link_to "時間内容新規登録", new_time_content_path, class: :nav_register__btn %>
        <%= search_form_for @p, url: keyword_search_time_content_index_path, class: "search-form", local: true do |f| %>
          <%= f.text_field :detail_cont, class: 'input-box', placeholder:'キーワードから探す' %>
          <button class="search-button">
            <%= image_submit_tag "search.png", class:"search-icon" %>
          </button>
        <% end %>
        <%= link_to '詳細検索', detail_search_time_content_index_path, class: "detail-search" %></li>
      </div>

      <div class="hidden_box">
        <label for="btn-text">グラフ表示/非表示</label>
        <input type="checkbox" id="btn-text"/>
        <div class="hidden_show">
          <div class="graph_title">
            <h3 class="day_graph_title">今日の仕事時間集計</h3>
            <h3 class="day_reduce_graph_title">今日の削減可能時間集計</h3>
            <h3 class="month_graph_title">今月の仕事時間集計</h3>
            <h3 class="month_reduce_graph_title">今月の削減可能時間集計</h3>
          </div>
          <div class="graph">
            <%= pie_chart @content_day_graph_data, colors: @background_colors, width: "200px", class: "day_graph" %>
            <%= pie_chart @content_day_reduce_graph_data, colors: @background_day_reduce_colors, width: "200px", class: "day_reduce_graph" %>
            <%= pie_chart @content_month_graph_data, colors: @background_month_colors, width: "200px", class: "month_graph" %>
            <%= pie_chart @content_month_reduce_graph_data, colors: @background_month_reduce_colors, width: "200px", class: "month_reduce_graph" %>
          </div>

          <div class="total_time_title">
            <div class="day_total_time_title">【今日の内容と合計時間】<br><br>
                <% @day_total_time.each do |day_total_time| %>
                  <span class="total_time">
                    <%= day_total_time[0] %>：<%= day_total_time[1] %>時間
                  </span>
                <% end %><br>
            </div>
            <div class="day_reduce_total_time_title">【今日の削減可能内容と時間】<br><br>
              <% @day_reduce_total_time.each do |day_reduce_total_time| %>
                <span class="total_time">
                  <%= day_reduce_total_time[0] %>：<%= day_reduce_total_time[1] %>時間
                </span>
              <% end %><br>
            </div>

            <div class="month_total_time_title">【今月の内容と合計時間】<br><br>
              <% @month_total_time.each do |month_total_time| %>
                <span class="total_time">
                  <%= month_total_time[0] %>：<%= month_total_time[1] %>時間
                </span>
              <% end %> <br>
            </div>

            <div class="month_reduce_total_time_title">【今月の削減可能内容と時間】<br><br>
              <% @month_reduce_total_time.each do |month_reduce_total_time| %>
                <span class="total_time">
                  <%= month_reduce_total_time[0] %>：<%= month_reduce_total_time[1] %>時間
                </span>
              <% end %>
            </div>
          </div>
          <div class="total_time_t">
            <div class="day_total_time_t">合計時間：
              <% if @day_total_time.present?%>
                <%= @day_total_time.values.inject(:+)%>時間
              <% else %>
                <%= @day_total_time.values.inject(:+)%>時間
              <% end %>
            </div>
            <div calss="day_total_reduse_time_t">合計削減時間：
              <% if @day_reduce_total_time.present?%>
                <%= @day_reduce_total_time.values.inject(:+)%>時間
              <% else %>
                <%= @day_reduce_total_time.values.inject(:+)%>時間
              <% end %>
            </div>
            <div class="month_total_time_t">合計時間：
              <% if @month_total_time.present?%>
                <%= @month_total_time.values.inject(:+)%>時間
              <% else %>
                <%= @month_total_time.values.inject(:+)%>時間
              <% end %>
            </div>
            <div class="month_total_reduce_time_t">合計削減時間：
              <% if @month_reduce_total_time.present?%>
                <%= @month_reduce_total_time.values.inject(:+)%>時間
              <% else %>
                <%= @month_reduce_total_time.values.inject(:+)%>時間
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="re_ch_btn">
        <%= link_to "時間内容新規登録", new_time_content_path, class: :nav_register__btn %>
        <%= link_to "その他データ内容確認", past_record_time_content_index_path, class: :nav_check__btn %>
      </div>
      <div class="hidden_box">
        <label for="btn-text2">カレンダー表示/非表示</label><br><br>
        <input type="checkbox" id="btn-text2"/>
        <div class="hidden_show">
          <%= month_calendar events: @time_contents do |date, time_contents| %>
            <%= link_to date, new_time_content_path, class: :nav_date_register__btn %>
            <% time_contents.each do |time_content| %>
              <div>
                <%= link_to time_content.content.name, time_content_path(time_content.id), class:"calendar_display" %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    <% else %>
      <div class="no_signed_in">
        <div class="sidebar">
            <h1>説明ページ</h1>
            <div class="submenu">
              <h2> 概要（クリックしてください）</h2>
              <ul class="hidden">
                <li>時間内容新規登録ページにて、「時間」・「仕事内容」・「仕事の実施可能な人」を選択し、詳細内容を入力します。<br>
  内容を登録すると内容に伴った円グラフとそれぞれの内容の合計時間がトップページに表示されます。</li>
              </ul>
            <div class="submenu">
              <h2> 基本的な使い方（クリックしてください）</h2>
              <ul class="hidden">
                <li><%=link_to "- 内容登録",  support_content_registration_time_content_index_path %></li>
                <li><%=link_to "- 検索機能",   support_search_time_content_index_path %></li>
                <li><%=link_to "- 過去内容確認",  support_record_time_content_index_path %></li>
                <li><%=link_to "- カレンダー確認",  support_calender_time_content_index_path %></li>
              </ul>
            </div>
          </div>
        <h1 class="day_graph_explain">デモ表示</h1>
        <img src="https://i.gyazo.com/202009a460c4b4468ea3f4c779fe506a.png" alt="Image from Gyazo" width="1075"/></a>
      </div><br>
      <%= link_to "時間内容新規登録", new_time_content_path, class: :nav_register__btn %>
      <%= link_to "その他データ内容確認", past_record_time_content_index_path, class: :nav_check__btn %>
       <div class="hidden_box">
        <label for="btn-text2">カレンダー表示/非表示</label><br><br>
        <input type="checkbox" id="btn-text2"/>
        <div class="hidden_show">
          <%= month_calendar events: @time_contents do |date, time_contents| %>
            <%= link_to date, new_time_content_path, class: :nav_date_register__btn %>
            <% time_contents.each do |time_content| %>
              <div>
                <%= link_to time_content.content.name, time_content_path(time_content.id), class:"calendar_display", id:"calendar_color" %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</main>

app/views/time_content/keyword_search.html.erb
<div class="search">
  <h1 class="search-result">
    検索結果
  </h1>
  <% if @results.length !=0 %>
    <% @results.each do |result| %>
      <li class="searched-list">
        日付：<%= result.start_time %>
        <br>
        実施時間： <%= result.begin_time.strftime( "%H:%M" ) %>〜<%= result.finish_time.strftime( "%H:%M" ) %>
        <br>
        実施内容：<%= result.content.name %>
        <br>
        実施できる人：<%= result.ensure.name %>
        <br>
        詳細内容：<%= result.detail %>
      </li><br>
      <div>
        <ul class="more_list">
          <li>
            <%= link_to "編集する", edit_time_content_path(result.id), class: "search_edit" %>
            <%= link_to '削除する', time_content_path(result.id), method: :delete, class: "search_delete", data: { confirm: '削除しますか？' } %>
          </li>
        </ul><br>
      </div>
    <% end %>
  <% else %>
    該当する項目はありません
  <% end %>
  <br>
  <%= link_to "時間内容新規登録", new_time_content_path, class: "back_register__btn" %>
  <%= link_to 'トップページへ戻る', root_path, class: "back_btn_top" %>
  <%= link_to '詳細検索ページへ戻る', detail_search_time_content_index_path, class: "back_btn_detail" %><br><br>
</div>

app/views/time_content/new.html.erb
<h1 class="time_content_title">今日の仕事内容と時間</h1>

<%= form_with(model: @time_content, url: time_content_index_path(@time_content.id), local: true) do |f| %>
<%= render 'shared/error_messages', model: f.object %>

  <div class="time_content_detail_title_1">
    <%= f.label :今日の日付, {:class => "date_title_style"} %>
    <%= f.label :開始時間, {:class => "begin_time_title_style"} %>
    <%= f.label :終了時間, {:class => "finish_time_title_style"} %> 
    <%= f.label :実施内容, {:class => "content_title_style"} %>
    <%= f.label :実施できる人, {:class => "ensure_title_style"} %>
  </div>

  <div class="time_and_content">
    <div class="date">
      <% if @time_content.start_time == nil %>
        <%= f.date_field :start_time, value: Date.today, class: "date_style"  %>
      <% elsif @time_content.start_time != nil %>
        <%= f.date_field :start_time, class: "date_style"  %>
      <% end %>
    </div>

    <div class="begin_time"> 
      <%= f.time_select(:begin_time, { prompt:'--', time_separator: ':', start_hour: 6, end_hour: 22, minute_step: 15, ignore_data: true}, {class: "begin_time_style"} ) %>
    </div>
 
    <div class="finish_time"> 
      <%= f.time_select(:finish_time, { prompt:'--', time_separator: ':', start_hour: 6, end_hour: 22, minute_step: 15, ignore_data: true}, {class: "begin_time_style"} ) %>
    </div>
    
    <div class="content">
      <%= f.collection_select(:content_id, Content.all, :id, :name, {}, {:class => "content_style"}) %>
    </div>

    <div class="ensure">
      <%= f.collection_select(:ensure_id, Ensure.all, :id, :name, {}, {:class => "ensure_style"}) %>
    </div>
  </div>

  <div class="time_content_detail_title_2">   
    <%= f.label :仕事詳細 %>
  </div>

  <div class="time_and_content_detail" >
    <div class="detial">
      <%= f.text_area :detail, {:class => "detail_style"} %>
    </div>
  </div>
    
  <div class="submit_btn">
    <div class="submit">
    <%= f.submit "登録", {:class => "submit_style"} %>
  </div>
  </div>

<% end %>

app/views/time_content/support_calender.html.erb
<div>
  <div><h1>【カレンダー確認】</h1>
    <h2>①カレンダー確認</h2>
   <a href="https://gyazo.com/2d0278e6b3a8882d2d88df453efbdb01"><img src="https://i.gyazo.com/2d0278e6b3a8882d2d88df453efbdb01.gif" alt="Image from Gyazo" width="1000"/></a> <br><br><br>
    <h2>②カレンダーで仕事内容の詳細確認</h2>
    <a href="https://gyazo.com/f79faaafde3368d41ad7bf83c7a61210"><img src="https://i.gyazo.com/f79faaafde3368d41ad7bf83c7a61210.gif" alt="Image from Gyazo" width="1000"/></a>
    <br><br><br>
  </div>
</div><br>