config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users', to: 'devise/registrations#new'
    post '/users/guest_sign_in', to: 'users#guest_sign_in'
  end
  root to: "time_content#index"
  resources :users, only: [:show]
  resources :time_content do
    collection do
     get 'keyword_search', 'detail_search'
     get 'past_record'
     get 'support_content_registration'
     get 'support_search'
     get 'support_record'
     get 'support_calender'
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>TimeManage</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.2/sweetalert.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  </head>

  <% if user_signed_in? %>
  <body onload=setTimeout('a()',1000)>
      <SCRIPT language="JavaScript">
      <!--
      
       function a() {
         if (window.name != "http://localhost:3000/") {
            
          swal("仕事内容の登録し忘れはありませんか？");
         
          window.name = "http://localhost:3000/";
         }
       }
     // -->
    //  <!--
    //    function a() {

    //        swal("仕事内容の登録し忘れはありませんか？");
    //    }
    //  // -->
     </SCRIPT>
  <% end %>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to(root_path, class: :title) do %>
              <%= image_tag 'TIME MANAGE.png' , size: '200x100'  %>
            <% end %>
          </div>
          <% if user_signed_in? %>
           <h2 class="greeting">
            今日は
            <%= Date.today.strftime("%Y年%m月%d日") %>です。<br>
            <%= current_user.name + "さん"%>
            <%= "、今日も一日頑張ろう！！" %>
            <% if (Time.now.strftime('%H:%M') >= '15:00') && (Time.now.strftime('%H:%M') < '17:30') %>
              <p class="counter">定時時間(17:30)まで残り<span class="counter_timer" id="timer"></span>です。</p>
            <% end %>
          </h2>
            <div class="nav__right">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__logout, data: { confirm: 'ログアウトしますか？' } %>
            </div>
          <% else %>
            <div class="nav__right">
              <%= link_to "新規登録", new_user_registration_path, class: :nav_up__btn %>
              <%= link_to "ログイン",  new_user_session_path, class: :nav_in__btn %>
              <%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, method: :post, class: :nav_test_in__btn %>
            </div>
          <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © TIME MANAGE All rights reserved.</p>
    </footer>
    <script>
      const hours = new Date().getHours();
      const minutes = new Date().getMinutes();
      const seconds = new Date().getSeconds();
        if(location.href === "http://localhost:3000/") {
          if(hours === 15) {
            if(minutes >= 0 && minutes < 15) {
              if(seconds >= 0 && seconds < 10) {
                swal("休憩してはどうですか？？");
              }
            }
          }
        }

        if(location.href === "http://localhost:3000/") {
          if(hours === 17) {
            if(minutes >= 15 && minutes < 25) {
              if(seconds >= 0 && seconds < 10) {
                swal("定時まで後少し、がんばれ！！");
              }
            }
          }
        }

        if(location.href === "http://localhost:3000/") {
          if(hours === 19) {
            if(minutes >= 45 && minutes <= 59) {
              if(seconds >= 0 && seconds < 10) {
                swal("もうすぐ20時です！！そろそろ、帰りませんか？？");
              }
            }
          }
        }

        function countdown(due) {
          const now = new Date();

          const rest = due.getTime() - now.getTime();
          const sec = Math.floor(rest / 1000) % 60;
          const min = Math.floor(rest / 1000 / 60) % 60;
          const hour = Math.floor(rest / 1000 / 60 / 60) % 24;
          const day = Math.floor(rest / 1000 / 60 / 60 / 24);
          const count = [day, hour, min, sec];

          return count;
        }

        let goal = new Date();
        goal.setHours(17);
        goal.setMinutes(30);
        goal.setSeconds(59);

        function recalc() {
          const counter = countdown(goal);
          const time = `${counter[1]}時間${counter[2]}分${counter[3]}秒`;
          document.getElementById('timer').textContent = time;
          refresh();
        }

        function refresh() {
          setTimeout(recalc,1000)
        }

        recalc();
    </script>

    <script>
      'use strict'

      $(document).ready(function(){
        $('.submenu h2').on('click', function(){
          $(this).next().toggleClass('hidden');
        } 
        );
      });
    </script>
  </body>
</html>